name: Docker Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: bencher

      - name: Build Docker image
        run: |
          cd bencher
          docker build -t bencher .

      - name: Run Docker container in background
        run: |
          docker run -d -p 50051:50051 bencher

      - name: Checkout bencherclient code
        uses: actions/checkout@v4
        with:
          repository: 'LeoIV/bencherclient'
          ref: 'master'
          token: ${{ secrets.BENCHERCLIENT_PAT }}
          path: bencherclient

      - name: Checkout python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          cd bencherclient
          poetry install --with dev

      - name: Run bencherclient
        run: |
          cd bencherclient
          poetry run python -m bencherclient -b robotpushing -p 1 1 1 1 1 1 1 1 1 1 1 1 1 1

      - name: Push to dockerhub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker tag bencher ${{ secrets.DOCKERHUB_USERNAME }}/bencher
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bencher

