name: Docker Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: bencher

      - name: Build Docker image
        run: |
          cd bencher
          docker build -t bencher .

      - name: Run Docker container in background
        run: |
          docker run -d -p 50051:50051 bencher

      - name: Checkout bencherclient code
        uses: actions/checkout@v4
        with:
          repository: 'LeoIV/bencherclient'
          ref: 'master'
          token: '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'
          path: bencherclient

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          cd bencherclient
          poetry install

      - name: Run bencherclient
        run: |
          cd bencherclient
          poetry run python -m bencherclient -b robotpushing -p 1 1 1 1 1 1 1 1 1 1 1 1 1 1

